version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/sesubway
permissions:
  - object: /home/ubuntu/sesubway
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 30
      runas: ubuntu
